/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Verify */
        get: operations["audit_verify_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document File */
        get: operations["get_document_file_api_v1_applications__application_id__documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents/{document_id}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Overlay */
        get: operations["get_document_overlay_api_v1_applications__application_id__documents__document_id__overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override Decision */
        post: operations["override_decision_api_v1_applications__application_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notice */
        get: operations["get_notice_api_v1_applications__application_id__notice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scorecard Meta */
        get: operations["get_scorecard_meta_api_v1_meta_scorecard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fraud/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fraud Graph
         * @description Reconstructs the document-reuse graph from `phash_collision` findings
         *     already persisted in fraud_findings -- no separate graph table exists;
         *     every edge's corroboration evidence is already in `evidence` (see
         *     app/services/fraud/service.py's `_run_phash_check`).
         */
        get: operations["get_fraud_graph_api_v1_fraud_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Demo Personas */
        get: operations["list_demo_personas_api_v1_demo_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/personas/{persona_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Demo Persona */
        post: operations["submit_demo_persona_api_v1_demo_personas__persona_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Does not touch the DB -- see /readyz for that.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdverseActionNotice */
        AdverseActionNotice: {
            /** Decision */
            decision: string;
            /** Generated At */
            generated_at: string;
            /** Applicant Reference */
            applicant_reference: string;
            /** Principal Reasons */
            principal_reasons?: {
                [key: string]: unknown;
            }[];
            /** What You Can Do */
            what_you_can_do?: string[];
            /** Basis Statement */
            basis_statement: string;
            /** Appeal Contact Placeholder */
            appeal_contact_placeholder: string;
            /** Non Discrimination Statement */
            non_discrimination_statement: string;
        };
        /** ApplicationDetail */
        ApplicationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Applicant Reference */
            applicant_reference: string;
            /** Applicant Name */
            applicant_name: string;
            /** Requested Line Inr */
            requested_line_inr: number;
            /** Eligible Line Inr */
            eligible_line_inr: number | null;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Error Code */
            error_code: string | null;
            /** Outcome */
            outcome: string | null;
            /** Final Outcome */
            final_outcome: string | null;
            /** Overridden By */
            overridden_by: string | null;
            /** Override Reason */
            override_reason: string | null;
            /** Score */
            score: number | null;
            /** Fraud Severity */
            fraud_severity: string | null;
            /** Data Completeness */
            data_completeness: number | null;
            /** Scorecard Version */
            scorecard_version: string | null;
            /** Policy Version */
            policy_version: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
            fraud_report: components["schemas"]["FraudReport"] | null;
            sanitization_report: components["schemas"]["SanitizationReport"] | null;
            score_breakdown: components["schemas"]["ScoreBreakdown"] | null;
            decision: components["schemas"]["Decision"] | null;
            precedents: components["schemas"]["PrecedentPanel"] | null;
            /** Recourse */
            recourse: components["schemas"]["RecourseAction"][];
            summary: components["schemas"]["SummaryResult"] | null;
            notice: components["schemas"]["AdverseActionNotice"] | null;
        };
        /** ApplicationListResponse */
        ApplicationListResponse: {
            /** Items */
            items: components["schemas"]["ApplicationSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ApplicationSummary */
        ApplicationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Applicant Reference */
            applicant_reference: string;
            /** Requested Line Inr */
            requested_line_inr: number;
            /** Eligible Line Inr */
            eligible_line_inr: number | null;
            /** Outcome */
            outcome: string | null;
            /** Final Outcome */
            final_outcome: string | null;
            /** Score */
            score: number | null;
            /** Fraud Severity */
            fraud_severity: string | null;
            /** Stage */
            stage: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditLogEntry */
        AuditLogEntry: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Event Type */
            event_type: string;
            /** Application Id */
            application_id: string | null;
            /** Applicant Id */
            applicant_id: string | null;
            /** Actor */
            actor: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** AuditLogListResponse */
        AuditLogListResponse: {
            /** Items */
            items: components["schemas"]["AuditLogEntry"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Body_create_application_api_v1_applications_post */
        Body_create_application_api_v1_applications_post: {
            /** Kyc */
            kyc: string;
            /** Gig Payout */
            gig_payout?: string | null;
            /** Utility Bill */
            utility_bill?: string | null;
            /** Bank Statement */
            bank_statement?: string | null;
        };
        /** Decision */
        Decision: {
            /** Outcome */
            outcome: string;
            /** Tier */
            tier: string;
            /** Eligible Line Inr */
            eligible_line_inr: number;
            /** Reason Codes */
            reason_codes: string[];
            /** Rules Fired */
            rules_fired: string[];
            /** Score */
            score: number;
            /** Fraud Severity */
            fraud_severity: string;
            /** Data Completeness */
            data_completeness: number;
        };
        /** DemoPersonaInfo */
        DemoPersonaInfo: {
            /** Persona Id */
            persona_id: string;
            /** Expected Outcome */
            expected_outcome: string;
            /** Notes */
            notes: string;
            /** Docs Present */
            docs_present: string[];
        };
        /**
         * DocumentRadar
         * @description Per-document tamper-radar summary (Phase 7's UI overlay reads this).
         */
        DocumentRadar: {
            /** Document Id */
            document_id?: string | null;
            /** Doc Type */
            doc_type: string;
            /** Radar Score */
            radar_score: number;
            /** Applicable Checks */
            applicable_checks: string[];
            /** Flagged Regions */
            flagged_regions?: number[][];
            /** Heatmap Storage Key */
            heatmap_storage_key?: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Doc Type */
            doc_type: string;
            /** Mime */
            mime: string;
            /** Extracted */
            extracted: {
                [key: string]: unknown;
            } | null;
            /** Extraction Confidence */
            extraction_confidence: number | null;
            /** Extraction Model */
            extraction_model: string | null;
            /** Forensic */
            forensic: {
                [key: string]: unknown;
            } | null;
        };
        /** Finding */
        Finding: {
            /** Check Name */
            check_name: string;
            /** Severity */
            severity: string;
            /** Penalty Points */
            penalty_points: number;
            /** Message */
            message: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Document Id */
            document_id?: string | null;
        };
        /** FraudReport */
        FraudReport: {
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Per Document Radar */
            per_document_radar: components["schemas"]["DocumentRadar"][];
            /** Trust Score */
            trust_score: number;
            /** Authenticity Score */
            authenticity_score: number;
            /** Severity */
            severity: string;
            /** Graph Edges */
            graph_edges?: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description One corroborated-or-not document-reuse edge, for Phase 7's syndicate graph.
         */
        GraphEdge: {
            /**
             * Applicant A
             * Format: uuid
             */
            applicant_a: string;
            /**
             * Applicant B
             * Format: uuid
             */
            applicant_b: string;
            /** Doc Type */
            doc_type: string;
            /** Hamming Distance */
            hamming_distance: number;
            /** Sha256 Match */
            sha256_match: boolean;
            /** Corroborated */
            corroborated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** OverrideRequest */
        OverrideRequest: {
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string;
        };
        /** PrecedentMatchOut */
        PrecedentMatchOut: {
            /**
             * Historical Id
             * Format: uuid
             */
            historical_id: string;
            /** Rank */
            rank: number;
            /** Similarity */
            similarity: number;
            /** Defaulted */
            defaulted: boolean;
            /** Cohort */
            cohort: string | null;
        };
        /** PrecedentPanel */
        PrecedentPanel: {
            /** Matches */
            matches: components["schemas"]["PrecedentMatchOut"][];
            /** Peer Default Rate */
            peer_default_rate: number;
            /** Peer Default Rate Weighted */
            peer_default_rate_weighted: number;
            /** Ci Lower */
            ci_lower: number;
            /** Ci Upper */
            ci_upper: number;
            /** Sample Size */
            sample_size: number;
            /** Agrees With Scorecard */
            agrees_with_scorecard: boolean | null;
        };
        /** RecourseAction */
        RecourseAction: {
            /** Feature */
            feature: string;
            /** Current */
            current: number | null;
            /** Target */
            target: number;
            /** Points Gain */
            points_gain: number;
            /** Resulting Score */
            resulting_score: number;
            /** Horizon Days */
            horizon_days: number | null;
            /** Text */
            text: string;
            /**
             * Actionable
             * @default true
             */
            actionable: boolean;
        };
        /**
         * RemovedField
         * @description One field the sanitizer stripped before scoring, and why. Phase 7's
         *     Responsible-AI Guardrail panel renders this list verbatim so an
         *     underwriter can see exactly what never reached the scorer.
         */
        RemovedField: {
            /** Field */
            field: string;
            /** Reason */
            reason: string;
        };
        /** SanitizationReport */
        SanitizationReport: {
            /** Removed */
            removed: components["schemas"]["RemovedField"][];
            /** Allowed */
            allowed: string[];
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Version */
            version: string;
            /** Base */
            base: number;
            /** Total */
            total: number;
            /** Factors */
            factors: components["schemas"]["ScoreFactor"][];
            /** Data Completeness */
            data_completeness: number;
        };
        /** ScoreFactor */
        ScoreFactor: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
            /** Bin Label */
            bin_label: string;
            /** Points */
            points: number;
            /** Max Up */
            max_up: number;
            /** Max Down */
            max_down: number;
            /** Direction */
            direction: string;
            /** Reason Code */
            reason_code: string;
        };
        /** SummaryResult */
        SummaryResult: {
            /** Text */
            text: string;
            /** Source */
            source: string;
            /** Model */
            model: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Verified */
            verified: boolean;
            /**
             * Sampling Params
             * @default {}
             */
            sampling_params: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyChainResponse */
        VerifyChainResponse: {
            /** Valid */
            valid: boolean;
            /** First Broken Id */
            first_broken_id: number | null;
            /** Checked */
            checked: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    audit_verify_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyChainResponse"];
                };
            };
        };
    };
    list_audit_log_api_v1_audit_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                application_id?: string | null;
                applicant_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_application_api_v1_applications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_api_v1_applications__application_id__documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_overlay_api_v1_applications__application_id__documents__document_id__overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_decision_api_v1_applications__application_id__override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notice_api_v1_applications__application_id__notice_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdverseActionNotice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scorecard_meta_api_v1_meta_scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_fraud_graph_api_v1_fraud_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_demo_personas_api_v1_demo_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoPersonaInfo"][];
                };
            };
        };
    };
    submit_demo_persona_api_v1_demo_personas__persona_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
